version: '3.5'

services:
  localstack:
    image: localstack/localstack:4.0.3
    ports:
      - '4566:4566'   # LocalStack Edge
    environment:
      - DEBUG=1
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
    volumes:
      - './localstack:/var/lib/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
