name: Code Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  publish-code-coverage:
    runs-on: ubuntu-latest
    env:
      JDK_VERSION: 17
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Generate coverage report
        run: ./gradlew test codeCoverageReport -Dorg.gradle.caching=false

      - name: Publish Coverage
        if: success()
        run: bash <(curl -s https://codecov.io/bash)
        shell: bash
